version: '2.4'

services:

  cassandra_1: &cassandra_base
    build:
      context: ./build/
    ports:
      - "${cassandra_ip_port:-127.0.0.1:9042-9044}:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra_1"
      CASSANDRA_HINTED_HANDOFF_ENABLED: "false"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 3s
      timeout: 2s
      retries: 60

  cassandra_2:
    <<: *cassandra_base
    depends_on:
      cassandra_1:
        condition: service_healthy

  cassandra_3:
    <<: *cassandra_base
    depends_on:
      cassandra_2:
        condition: service_healthy
